version: '3.8'

services:
  uptime-kuma:
    container_name: uptime-kuma-dev
    image: louislam/uptime-kuma:nightly2@sha256:c624f89d1525b564eb84c689694f37b89ccfffc2b19709ca1c967df1438c0fdc
    volumes:
      #- ./data:/app/data
      - ../server:/app/server
      - ../db:/app/db
    ports:
      - "3001:3001"  # <Host Port>:<Container Port>
      - "3307:3306"

