name: Merge Conflict Labeler

on:
  push:
    branches:
      - master
  pull_request_target:
    branches:
      - master
    types: [synchronize]

jobs:
  label:
    name: Labeling
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'louislam/uptime-kuma' }}
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Apply label
        uses: eps1lon/actions-label-merge-conflict@1b1b1fcde06a9b3d089f3464c96417961dde1168 # v3.0.2
        with:
          dirtyLabel: 'needs:resolve-merge-conflict'
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
